import {DEV_URL, CENTRAL_URL, IS_STAGING, PRODUCT_KEY,IMAGE_STORAGE_URL} from '@env';

export const Config = {
  API_URL: IS_STAGING ? DEV_URL : CENTRAL_URL,
  IS_STAGING: IS_STAGING,
  PRODUCT_KEY,
  IMAGE_STORAGE_URL,
};
