export const Images = {
  darkLogo: require('@assets/images/darkAppLogo.png'),
  lightLogo: require('@assets/images/lightAppLogo.png'),
  imgDefaultUser: require('@assets/images/DefaultUser.png'),
  appLogo: require('@assets/images/appLogo.png'),
  background: require('@assets/images/background.jpg'),
  imgIcTelephone: require('@assets/images/social-media-image/imgPhone.png'),
  imgEmail: require('@assets/images/social-media-image/imgEmail.png'),
  imgInstagram: require('@assets/images/social-media-image/imgInstagram.png'),
  imgLocation: require('@assets/images/social-media-image/imgLocation.png'),
  imgTwitter: require('@assets/images/social-media-image/imgTwitter.png'),
  imgWhatsApp: require('@assets/images/social-media-image/imgWhatsApp.png'),
  imgWorld: require('@assets/images/social-media-image/imgWorld.png'),
  imgFacebook: require('@assets/images/social-media-image/imgFacebook.png'),
  seanebCoverGalery: require('@assets/images/seanebCoverGalery.jpg'),
};
