import {StyleSheet} from 'react-native';
import {size} from '@config/Sizes';
import {fontFamily, fontSize} from '@config/theme';
import {useThemeContext} from '@contexts/themeContext';

const GetStyles = () => {
  const {color} = useThemeContext();
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: color.white,
    },
    profileRoot: {
      flexGrow: 1,
      backgroundColor: color.white,
      paddingHorizontal: size.moderateScale(16),
      paddingTop: size.moderateScale(24),
      paddingBottom: size.moderateScale(40),
    },
    profileHeader: {
      alignItems: 'flex-start',
      marginBottom: size.moderateScale(10),
    },
    profileCont: {flexDirection: 'row', gap: 10},
    profileAvatar: {
      width: size.moderateScale(50),
      height: size.moderateScale(50),
      borderRadius: size.moderateScale(25),
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: size.moderateScale(16),
      position: 'relative',
      backgroundColor: color.blue,
    },
    profileAvatarText: {
      color: color.white,
      fontFamily: fontFamily.bold,
      fontSize: fontSize.smallMedium,
    },
    profileContainer: {
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    profileName: {
      fontFamily: fontFamily.bold,
      fontSize: fontSize.smallMedium,
      color: color.black,
    },
    profileHeadline: {
      fontFamily: fontFamily.light,
      fontSize: fontSize.smallerMedium,
      color: color.gray900,
    },
    metaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
    },
    metaItem: {
      flexDirection: 'row',
      alignItems: 'center',
      marginRight: size.moderateScale(16),
    },
    metaText: {
      fontFamily: fontFamily.light,
      fontSize: fontSize.smallerMedium,
      color: color.gray900,
      marginLeft: size.moderateScale(6),
    },
    sectionContainer: {
      marginBottom: size.moderateScale(10),
    },
    sectionTitle: {
      fontFamily: fontFamily.bold,
      fontSize: fontSize.small,
      color: color.black,
      letterSpacing: 1,
      marginBottom: size.moderateScale(5),
      flex: 1,
    },
    aboutText: {
      fontFamily: fontFamily.regular,
      fontSize: fontSize.littleMedium,
      color: color.black,
      lineHeight: 22,
    },
    infoGrid: {
      gap: 10,
    },
    infoCard: {
      flex: 1,
      backgroundColor: `${color.gray200}30`,
      borderRadius: size.moderateScale(12),
      padding: size.moderateScale(12),
      flexDirection: 'row',
      alignItems: 'center',
    },
    infoIconWrapper: {
      width: size.moderateScale(36),
      height: size.moderateScale(36),
      backgroundColor: color.white,
      borderRadius: size.moderateScale(10),
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: size.moderateScale(12),
      borderWidth: 1,
      borderColor: color.gray200,
    },
    educationWrapper: {
      width: size.moderateScale(36),
      height: size.moderateScale(36),
      backgroundColor: `${color.green}20`,
      borderRadius: size.moderateScale(10),
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: size.moderateScale(12),
      borderWidth: 1,
      borderColor: color.green,
    },
    infoTextWrapper: {
      flex: 1,
    },
    infoLabel: {
      fontFamily: fontFamily.regular,
      fontSize: fontSize.verySmall,
      color: color.black,
      textTransform: 'uppercase',
      marginBottom: size.moderateScale(2),
    },
    infoValue: {
      fontFamily: fontFamily.semiBold,
      fontSize: fontSize.smallerMedium,
      color: color.black,
    },
    skillsWrapper: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    profileSkillTag: {
      backgroundColor: `${color.gray200}30`,
      paddingHorizontal: size.moderateScale(12),
      paddingVertical: size.moderateScale(8),
      borderRadius: size.moderateScale(20),
      marginRight: size.moderateScale(10),
      marginBottom: size.moderateScale(10),
    },
    profileSkillText: {
      fontFamily: fontFamily.regular,
      fontSize: fontSize.smallerMedium,
      color: color.black,
    },
    timelineRow: {
      flexDirection: 'row',
      marginBottom: size.moderateScale(16),
    },
    timelineGraphicContainer: {
      width: size.moderateScale(40),
      alignItems: 'center',
    },
    timelineDot: {
      width: size.moderateScale(14),
      height: size.moderateScale(14),
      borderRadius: size.moderateScale(7),
      borderWidth: 2,
      backgroundColor: color.white,
      marginTop: size.moderateScale(24),
      zIndex: 2,
    },
    timelineLine: {
      width: 1.5,
      position: 'absolute',
      top: size.moderateScale(38),
      bottom: -size.moderateScale(32),
      zIndex: 1,
    },
    timelineCard: {
      flex: 1,
      borderWidth: 1,
      borderRadius: size.moderateScale(10),
      padding: size.moderateScale(12),
    },
    cardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: size.moderateScale(4),
    },
    jobTitle: {
      fontFamily: fontFamily.bold,
      fontSize: fontSize.littleMedium,
      color: color.black,
    },
    currentBadge: {
      paddingHorizontal: size.moderateScale(8),
      paddingVertical: size.moderateScale(4),
      borderRadius: size.moderateScale(6),
    },
    currentBadgeText: {
      color: color.white,
      fontSize: 9,
      fontFamily: fontFamily.bold,
      letterSpacing: 0.5,
    },
    companyName: {
      fontFamily: fontFamily.light,
      fontSize: fontSize.smallerMedium,
      color: color.black,
      marginBottom: size.moderateScale(8),
    },
    metaDataRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
    },
    locationRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    locationText: {
      fontFamily: fontFamily.regular,
      fontSize: fontSize.verySmallMedium,
      color: color.gray200,
      marginLeft: size.moderateScale(4),
    },
    timelineCardGrey: statusColor => ({
      backgroundColor: `${statusColor}10`,
      borderColor: statusColor,
    }),
    timelineItem: {
      flexDirection: 'row',
      marginBottom: size.moderateScale(16),
      alignItems: 'flex-start',
    },
    timelineDotContainer: {
      width: 24,
      height: 24,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: color.white,
      zIndex: 1,
      borderRadius: 12,
      alignSelf: 'center',
    },
    timelineDot1: {
      width: 10,
      height: 10,
      borderRadius: 5,
    },
    timelineCard1: {
      flex: 1,
      marginLeft: 10,
      padding: size.moderateScale(10),
      borderRadius: size.moderateScale(10),
      borderWidth: 1,
      gap: size.moderateScale(8),
    },
    timelineTitle: {
      fontSize: fontSize.smallerMedium,
      fontFamily: fontFamily.semiBold,
    },
    timelineMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 12,
    },
    metaItem1: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    metaText1: {
      fontSize: fontSize.verySmall,
      color: color.gray900,
      marginLeft: 4,
    },
    badge: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 8,
      paddingVertical: 6,
      borderRadius: 12,
      borderWidth: 0.5,
    },
    timelineContainer: {
      position: 'relative',
    },
    verticalLine: {
      position: 'absolute',
      left: 11,
      top: 15,
      bottom: 20,
      width: 1,
      backgroundColor: color.gray,
      zIndex: 0,
    },
    progressContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      position: 'relative',
      paddingVertical: 10,
      marginBottom: 10,
    },
    progressLineBackground: {
      position: 'absolute',
      top: 24,
      left: 20,
      right: 20,
      height: 3,
      backgroundColor: color.gray,
      zIndex: 0,
    },
    progressStep: {
      alignItems: 'center',
      zIndex: 1,
      flex: 1,
    },
    progressCircle: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
    },
    numText: {color: color.black, fontSize: 10},
    progressLabel: {
      fontSize: fontSize.verySmall,
      fontFamily: fontFamily.regular,
      color: color.black,
    },
    statusPill: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 20,
      borderWidth: 1,
      backgroundColor: color.white,
    },
    statusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      marginRight: 6,
    },
    statusText: {
      fontSize: fontSize.mediumSmall,
      fontFamily: fontFamily.semiBold,
      marginRight: 4,
    },
    popoverStyle: {
      backgroundColor: color.sheetColor,
      borderRadius: size.moderateScale(12),
    },
    popoverInnerContainer: {
      minWidth: size.moderateScale(160),
      paddingVertical: size.moderateScale(8),
    },
    statusMenuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: size.moderateScale(8),
      paddingHorizontal: size.moderateScale(14),
    },
    statusMenuText: {
      fontSize: fontSize.verySmallMedium,
      fontFamily: fontFamily.regular,
      color: color.black,
      paddingLeft: size.moderateScale(10),
    },
    sectionView: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    emptyCont: {alignItems: 'center', marginTop: 50},
    emptyText: {
      color: color.gray900,
      fontSize: fontSize.smallerMedium,
      fontFamily: fontFamily.semiBold,
    },
    editCont: {
      padding: 5,
      gap: 5,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderRadius: 12,
      borderColor: color.black,
      paddingHorizontal: 10,
    },
    noteText: {
      color: color.gray900,
      fontSize: fontSize.smallerMedium,
      fontFamily: fontFamily.regular,
      marginBottom: size.moderateScale(15),
    },
  });
};

export default GetStyles;
